name: "Pull Request"
on: [pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set context
      uses: azure/k8s-actions/k8s-set-context@master
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
    - name: Deploy Kubeflow
      uses: TenSt/install-kubeflow@tenst-patch-1
      with:
        config: "https://raw.githubusercontent.com/kubeflow/kubeflow/v0.6-branch/bootstrap/config/kfctl_existing_arrikto.0.6.2.yaml"
        username: "stepan.maksymchuk@ventus.ag"
        password: "1234567890"